import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

const productsData = [
  {
    productId: "react-vision",
    name: "Nike React Vision",
    brand: "Nike",
    basePrice: 139.99,
    category: "Shoes",
    gender: "Male",
    variations: [
      {
        id: "react-vision-white",
        colorway: "Blanc",
        price: 139.99,
        salePrice: 109.99,
        thumbnailUrl: "/sneakers/thumbnails/NIKE_REACT_VISION_white_sm.webp",
        largeUrl: "/sneakers/large/NIKE_REACT_VISION_white.webp",
        alt: "Nike React Vision Blanc",
        sizes: [
          { size: "38", inStock: true, quantity: 5 },
          { size: "39", inStock: false, quantity: 0 },
          { size: "40", inStock: true, quantity: 8 },
          { size: "41", inStock: true, quantity: 12 },
          { size: "42", inStock: true, quantity: 6 },
          { size: "43", inStock: true, quantity: 15 },
          { size: "44", inStock: true, quantity: 4 },
          { size: "45", inStock: true, quantity: 7 },
          { size: "46", inStock: false, quantity: 3 },
          { size: "47", inStock: true, quantity: 2 },
        ],
      },
      {
        id: "react-vision-black",
        colorway: "Noir",
        price: 139.99,
        salePrice: 109.99,
        thumbnailUrl: "/sneakers/thumbnails/NIKE_REACT_VISION_black_sm.webp",
        largeUrl: "/sneakers/large/NIKE_REACT_VISION_black.webp",
        alt: "Nike React Vision Noir",
        sizes: [
          { size: "38", inStock: false, quantity: 0 },
          { size: "39", inStock: true, quantity: 1 },
          { size: "40", inStock: true, quantity: 3 },
          { size: "41", inStock: true, quantity: 5 },
          { size: "42", inStock: true, quantity: 8 },
          { size: "43", inStock: true, quantity: 2 },
          { size: "44", inStock: true, quantity: 4 },
          { size: "45", inStock: false, quantity: 0 },
          { size: "46", inStock: true, quantity: 6 },
          { size: "47", inStock: true, quantity: 3 },
        ],
      },
    ],
  },
  {
    productId: "air-force",
    name: "Nike Air Force 1",
    brand: "Nike",
    basePrice: 119.99,
    category: "Shoes",
    gender: "Male",
    variations: [
      {
        id: "air-force-white",
        colorway: "Blanc",
        price: 119.99,
        salePrice: null,
        thumbnailUrl: "/sneakers/thumbnails/AIR_FORCE_1_'07_white_sm.webp",
        largeUrl: "/sneakers/large/AIR_FORCE_1_'07_white.webp",
        alt: "Nike Air Force 1 Blanc",
        sizes: [
          { size: "38", inStock: true, quantity: 3 },
          { size: "39", inStock: false, quantity: 6 },
          { size: "40", inStock: true, quantity: 8 },
          { size: "41", inStock: true, quantity: 10 },
          { size: "42", inStock: true, quantity: 4 },
          { size: "43", inStock: true, quantity: 11 },
          { size: "44", inStock: true, quantity: 4 },
          { size: "45", inStock: true, quantity: 6 },
          { size: "46", inStock: false, quantity: 1 },
          { size: "47", inStock: true, quantity: 0 },
        ],
      },
      {
        id: "air-force-black",
        colorway: "Noir",
        price: 119.99,
        salePrice: null,
        thumbnailUrl: "/sneakers/thumbnails/AIR_FORCE_1_'07_black_sm.webp",
        largeUrl: "/sneakers/large/AIR_FORCE_1_'07_black.webp",
        alt: "Nike Air Force 1 Noir",
        sizes: [
          { size: "38", inStock: true, quantity: 0 },
          { size: "39", inStock: false, quantity: 3 },
          { size: "40", inStock: true, quantity: 7 },
          { size: "41", inStock: true, quantity: 8 },
          { size: "42", inStock: true, quantity: 7 },
          { size: "43", inStock: true, quantity: 10 },
          { size: "44", inStock: true, quantity: 3 },
          { size: "45", inStock: true, quantity: 6 },
          { size: "46", inStock: false, quantity: 4 },
          { size: "47", inStock: true, quantity: 2 },
        ],
      },
      {
        id: "air-force-white-black",
        colorway: "Blanc/Noir",
        price: 119.99,
        salePrice: null,
        thumbnailUrl:
          "/sneakers/thumbnails/AIR_FORCE_1_'07_white_black_sm.webp",
        largeUrl: "/sneakers/large/AIR_FORCE_1_'07_white_black.webp",
        alt: "Nike Air Force 1 Blanc/Noir",
        sizes: [
          { size: "38", inStock: true, quantity: 5 },
          { size: "39", inStock: false, quantity: 7 },
          { size: "40", inStock: true, quantity: 5 },
          { size: "41", inStock: true, quantity: 4 },
          { size: "42", inStock: true, quantity: 11 },
          { size: "43", inStock: true, quantity: 6 },
          { size: "44", inStock: true, quantity: 0 },
          { size: "45", inStock: true, quantity: 0 },
          { size: "46", inStock: false, quantity: 2 },
          { size: "47", inStock: true, quantity: 7 },
        ],
      },
      {
        id: "air-force-cream",
        colorway: "Crème",
        price: 119.99,
        salePrice: null,
        thumbnailUrl: "/sneakers/thumbnails/AIR_FORCE_1_'07_cream_sm.webp",
        largeUrl: "/sneakers/large/AIR_FORCE_1_'07_cream.webp",
        alt: "Nike Air Force 1 Crème",
        sizes: [
          { size: "38", inStock: true, quantity: 3 },
          { size: "39", inStock: false, quantity: 10 },
          { size: "40", inStock: true, quantity: 0 },
          { size: "41", inStock: true, quantity: 4 },
          { size: "42", inStock: true, quantity: 11 },
          { size: "43", inStock: true, quantity: 7 },
          { size: "44", inStock: true, quantity: 0 },
          { size: "45", inStock: true, quantity: 3 },
          { size: "46", inStock: false, quantity: 1 },
          { size: "47", inStock: true, quantity: 3 },
        ],
      },
    ],
  },
  {
    productId: "air-max-90-drift",
    name: "Nike Air Max 90 Drift",
    brand: "Nike",
    basePrice: 149.99,
    category: "Shoes",
    gender: "Male",
    variations: [
      {
        id: "air-max-90-drift-black",
        colorway: "Noir",
        price: 149.99,
        salePrice: 119.99,
        thumbnailUrl: "/sneakers/thumbnails/AIR_MAX_90_DRIFT_black_sm.webp",
        largeUrl: "/sneakers/large/AIR_MAX_90_DRIFT_black.webp",
        alt: "Nike Air Max 90 Drift Noir",
        sizes: [
          { size: "38", inStock: true, quantity: 0 },
          { size: "39", inStock: false, quantity: 3 },
          { size: "40", inStock: true, quantity: 0 },
          { size: "41", inStock: true, quantity: 10 },
          { size: "42", inStock: true, quantity: 5 },
          { size: "43", inStock: true, quantity: 11 },
          { size: "44", inStock: true, quantity: 3 },
          { size: "45", inStock: true, quantity: 5 },
          { size: "46", inStock: false, quantity: 3 },
          { size: "47", inStock: true, quantity: 0 },
        ],
      },
      {
        id: "air-max-90-drift-brown",
        colorway: "Marron",
        price: 149.99,
        salePrice: 119.99,
        thumbnailUrl: "/sneakers/thumbnails/AIR_MAX_90_DRIFT_brown_sm.webp",
        largeUrl: "/sneakers/large/AIR_MAX_90_DRIFT_brown.webp",
        alt: "Nike Air Max 90 Drift Marron",
        sizes: [
          { size: "38", inStock: false, quantity: 2 },
          { size: "39", inStock: true, quantity: 5 },
          { size: "40", inStock: true, quantity: 7 },
          { size: "41", inStock: true, quantity: 9 },
          { size: "42", inStock: true, quantity: 13 },
          { size: "43", inStock: true, quantity: 4 },
          { size: "44", inStock: true, quantity: 4 },
          { size: "45", inStock: false, quantity: 2 },
          { size: "46", inStock: true, quantity: 3 },
          { size: "47", inStock: true, quantity: 0 },
        ],
      },
    ],
  },
  {
    productId: "air-max-90-ltr",
    name: "Nike Air Max 90 LTR",
    brand: "Nike",
    basePrice: 149.99,
    category: "Shoes",
    gender: "Male",
    variations: [
      {
        id: "air-max-90-ltr-black",
        colorway: "Noir",
        price: 149.99,
        salePrice: null,
        thumbnailUrl: "/sneakers/thumbnails/AIR_MAX_90_LTR_black_sm.webp",
        largeUrl: "/sneakers/large/AIR_MAX_90_LTR_black.webp",
        alt: "Nike Air Max 90 LTR Noir",
        sizes: [
          { size: "38", inStock: true, quantity: 0 },
          { size: "39", inStock: false, quantity: 3 },
          { size: "40", inStock: true, quantity: 9 },
          { size: "41", inStock: true, quantity: 10 },
          { size: "42", inStock: true, quantity: 5 },
          { size: "43", inStock: true, quantity: 11 },
          { size: "44", inStock: true, quantity: 3 },
          { size: "45", inStock: true, quantity: 5 },
          { size: "46", inStock: false, quantity: 3 },
          { size: "47", inStock: true, quantity: 0 },
        ],
      },
      {
        id: "air-max-90-ltr-white",
        colorway: "Blanc",
        price: 149.99,
        salePrice: null,
        thumbnailUrl: "/sneakers/thumbnails/AIR_MAX_90_LTR_white_sm.webp",
        largeUrl: "/sneakers/large/AIR_MAX_90_LTR_white.webp",
        alt: "Nike Air Max 90 LTR Blanc",
        sizes: [
          { size: "38", inStock: false, quantity: 2 },
          { size: "39", inStock: true, quantity: 5 },
          { size: "40", inStock: true, quantity: 7 },
          { size: "41", inStock: true, quantity: 9 },
          { size: "42", inStock: true, quantity: 13 },
          { size: "43", inStock: true, quantity: 4 },
          { size: "44", inStock: true, quantity: 4 },
          { size: "45", inStock: false, quantity: 2 },
          { size: "46", inStock: true, quantity: 3 },
          { size: "47", inStock: true, quantity: 0 },
        ],
      },
    ],
  },
  {
    productId: "jordan-spizike",
    name: "Jordan Spizike Low",
    brand: "Nike",
    basePrice: 169.99,
    category: "Shoes",
    gender: "Male",
    variations: [
      {
        id: "jordan-spizike-low",
        colorway: "Noir/Blanc/Bleu/Rouge",
        price: 169.99,
        salePrice: null,
        thumbnailUrl: "/sneakers/thumbnails/JORDAN_SPIZIKE_LOW_SE_sm.webp",
        largeUrl: "/sneakers/large/JORDAN_SPIZIKE_LOW_SE.webp",
        alt: "Jordan Spizike Low Noir/Blanc/Bleu/Rouge",
        sizes: [
          { size: "38", inStock: true, quantity: 0 },
          { size: "39", inStock: false, quantity: 0 },
          { size: "40", inStock: true, quantity: 4 },
          { size: "41", inStock: true, quantity: 8 },
          { size: "42", inStock: true, quantity: 0 },
          { size: "43", inStock: true, quantity: 3 },
          { size: "44", inStock: true, quantity: 0 },
          { size: "45", inStock: true, quantity: 5 },
          { size: "46", inStock: false, quantity: 0 },
          { size: "47", inStock: true, quantity: 0 },
        ],
      },
    ],
  },
  {
    productId: "air-max-95",
    name: "Nike Air Max 95",
    brand: "Nike",
    basePrice: 189.99,
    category: "Shoes",
    gender: "Male",
    variations: [
      {
        id: "air-max-95-white",
        colorway: "Blanc",
        price: 189.99,
        salePrice: 149.99,
        thumbnailUrl: "/sneakers/thumbnails/NIKE_AIR_MAX_95_white_sm.webp",
        largeUrl: "/sneakers/large/NIKE_AIR_MAX_95_white.webp",
        alt: "Nike Air Max 95 Blanc",
        sizes: [
          { size: "38", inStock: true, quantity: 5 },
          { size: "39", inStock: false, quantity: 0 },
          { size: "40", inStock: true, quantity: 8 },
          { size: "41", inStock: true, quantity: 12 },
          { size: "42", inStock: true, quantity: 6 },
          { size: "43", inStock: true, quantity: 15 },
          { size: "44", inStock: true, quantity: 4 },
          { size: "45", inStock: true, quantity: 7 },
          { size: "46", inStock: false, quantity: 3 },
          { size: "47", inStock: true, quantity: 2 },
        ],
      },
      {
        id: "air-max-95-black",
        colorway: "Noir",
        price: 189.99,
        salePrice: 149.99,
        thumbnailUrl: "/sneakers/thumbnails/NIKE_AIR_MAX_95_black_sm.webp",
        largeUrl: "/sneakers/large/NIKE_AIR_MAX_95_black.webp",
        alt: "Nike Air Max 95 Noir",
        sizes: [
          { size: "38", inStock: false, quantity: 3 },
          { size: "39", inStock: true, quantity: 7 },
          { size: "40", inStock: true, quantity: 3 },
          { size: "41", inStock: true, quantity: 5 },
          { size: "42", inStock: true, quantity: 14 },
          { size: "43", inStock: true, quantity: 9 },
          { size: "44", inStock: true, quantity: 8 },
          { size: "45", inStock: false, quantity: 0 },
          { size: "46", inStock: true, quantity: 6 },
          { size: "47", inStock: true, quantity: 4 },
        ],
      },
      {
        id: "air-max-95-og",
        colorway: "Noir/Rouge",
        price: 189.99,
        salePrice: 149.99,
        thumbnailUrl: "/sneakers/thumbnails/NIKE_AIR_MAX_95_OG_sm.webp",
        largeUrl: "/sneakers/large/NIKE_AIR_MAX_95_OG.webp",
        alt: "Nike Air Max 95 Noir/Rouge",
        sizes: [
          { size: "38", inStock: false, quantity: 0 },
          { size: "39", inStock: true, quantity: 1 },
          { size: "40", inStock: true, quantity: 3 },
          { size: "41", inStock: true, quantity: 5 },
          { size: "42", inStock: true, quantity: 8 },
          { size: "43", inStock: true, quantity: 2 },
          { size: "44", inStock: true, quantity: 4 },
          { size: "45", inStock: false, quantity: 0 },
          { size: "46", inStock: true, quantity: 6 },
          { size: "47", inStock: true, quantity: 0 },
        ],
      },
    ],
  },
  {
    productId: "cortez",
    name: "Nike Cortez",
    brand: "Nike",
    basePrice: 99.99,
    category: "Shoes",
    gender: "Male",
    variations: [
      {
        id: "cortez-white",
        colorway: "Blanc/Bleu",
        price: 99.99,
        salePrice: null,
        thumbnailUrl: "/sneakers/thumbnails/NIKE_CORTEZ_sm.webp",
        largeUrl: "/sneakers/large/NIKE_CORTEZ.webp",
        alt: "Nike Cortez Blanc/Bleu",
        sizes: [
          { size: "38", inStock: true, quantity: 3 },
          { size: "39", inStock: false, quantity: 5 },
          { size: "40", inStock: true, quantity: 4 },
          { size: "41", inStock: true, quantity: 14 },
          { size: "42", inStock: true, quantity: 11 },
          { size: "43", inStock: true, quantity: 7 },
          { size: "44", inStock: true, quantity: 2 },
          { size: "45", inStock: true, quantity: 8 },
          { size: "46", inStock: false, quantity: 1 },
          { size: "47", inStock: true, quantity: 0 },
        ],
      },
    ],
  },
  {
    productId: "ozweego",
    name: "Adidas Ozweego",
    brand: "Adidas",
    basePrice: 119.99,
    category: "Shoes",
    gender: "Male",
    variations: [
      {
        id: "ozweego-beige",
        colorway: "Beige",
        price: 119.99,
        salePrice: null,
        thumbnailUrl: "/sneakers/thumbnails/OZWEEGO_Beige_FX6029_sm.webp",
        largeUrl: "/sneakers/large/OZWEEGO_Beige_FX6029.webp",
        alt: "Adidas Ozweego Beige",
        sizes: [
          { size: "38", inStock: true, quantity: 0 },
          { size: "39", inStock: false, quantity: 3 },
          { size: "40", inStock: true, quantity: 9 },
          { size: "41", inStock: true, quantity: 10 },
          { size: "42", inStock: true, quantity: 5 },
          { size: "43", inStock: true, quantity: 11 },
          { size: "44", inStock: true, quantity: 3 },
          { size: "45", inStock: true, quantity: 5 },
          { size: "46", inStock: false, quantity: 3 },
          { size: "47", inStock: true, quantity: 0 },
        ],
      },
      {
        id: "ozweego-black",
        colorway: "Noir",
        price: 119.99,
        salePrice: null,
        thumbnailUrl: "/sneakers/thumbnails/OZWEEGO_Noir_EE6999_sm.webp",
        largeUrl: "/sneakers/large/OZWEEGO_Noir_EE6999.webp",
        alt: "Adidas Ozweego Noir",
        sizes: [
          { size: "38", inStock: false, quantity: 2 },
          { size: "39", inStock: true, quantity: 5 },
          { size: "40", inStock: true, quantity: 7 },
          { size: "41", inStock: true, quantity: 9 },
          { size: "42", inStock: true, quantity: 13 },
          { size: "43", inStock: true, quantity: 4 },
          { size: "44", inStock: true, quantity: 4 },
          { size: "45", inStock: false, quantity: 2 },
          { size: "46", inStock: true, quantity: 3 },
          { size: "47", inStock: true, quantity: 0 },
        ],
      },
    ],
  },
  {
    productId: "samba-og",
    name: "Adidas Samba OG",
    brand: "Adidas",
    basePrice: 119.99,
    category: "Shoes",
    gender: "Male",
    variations: [
      {
        id: "samba-og-white",
        colorway: "Blanc",
        price: 119.99,
        salePrice: 109.99,
        thumbnailUrl: "/sneakers/thumbnails/Samba_OG_Blanc_B75806_sm.webp",
        largeUrl: "/sneakers/large/Samba_OG_Blanc_B75806.webp",
        alt: "Adidas Samba OG Blanc",
        sizes: [
          { size: "38", inStock: true, quantity: 0 },
          { size: "39", inStock: false, quantity: 3 },
          { size: "40", inStock: true, quantity: 9 },
          { size: "41", inStock: true, quantity: 10 },
          { size: "42", inStock: true, quantity: 5 },
          { size: "43", inStock: true, quantity: 11 },
          { size: "44", inStock: true, quantity: 3 },
          { size: "45", inStock: true, quantity: 5 },
          { size: "46", inStock: false, quantity: 3 },
          { size: "47", inStock: true, quantity: 0 },
        ],
      },
      {
        id: "samba-og-black",
        colorway: "Noir",
        price: 119.99,
        salePrice: 109.99,
        thumbnailUrl:
          "/sneakers/thumbnails/Samba_OG_x_Jeremy_Scott_Noir_JQ8835_sm.webp",
        largeUrl: "/sneakers/large/Samba_OG_x_Jeremy_Scott_Noir_JQ8835.webp",
        alt: "Adidas Samba OG Noir",
        sizes: [
          { size: "38", inStock: false, quantity: 2 },
          { size: "39", inStock: true, quantity: 5 },
          { size: "40", inStock: true, quantity: 7 },
          { size: "41", inStock: true, quantity: 9 },
          { size: "42", inStock: true, quantity: 13 },
          { size: "43", inStock: true, quantity: 4 },
          { size: "44", inStock: true, quantity: 4 },
          { size: "45", inStock: false, quantity: 2 },
          { size: "46", inStock: true, quantity: 3 },
          { size: "47", inStock: true, quantity: 0 },
        ],
      },
      {
        id: "samba-og-beige",
        colorway: "Beige",
        price: 119.99,
        salePrice: 109.99,
        thumbnailUrl: "/sneakers/thumbnails/Samba_OG_Beige_JS3830_sm.webp",
        largeUrl: "/sneakers/large/Samba_OG_Beige_JS3830.webp",
        alt: "Adidas Samba OG Beige",
        sizes: [
          { size: "38", inStock: true, quantity: 2 },
          { size: "39", inStock: false, quantity: 1 },
          { size: "40", inStock: true, quantity: 9 },
          { size: "41", inStock: true, quantity: 8 },
          { size: "42", inStock: true, quantity: 3 },
          { size: "43", inStock: true, quantity: 11 },
          { size: "44", inStock: true, quantity: 3 },
          { size: "45", inStock: true, quantity: 4 },
          { size: "46", inStock: false, quantity: 0 },
          { size: "47", inStock: true, quantity: 0 },
        ],
      },
      {
        id: "samba-og-gray",
        colorway: "Gris",
        price: 119.99,
        salePrice: 109.99,
        thumbnailUrl: "/sneakers/thumbnails/Samba_OG_Gris_JR0886_sm.webp",
        largeUrl: "/sneakers/large/Samba_OG_Gris_JR0886.webp",
        alt: "Adidas Samba OG Gris",
        sizes: [
          { size: "38", inStock: false, quantity: 0 },
          { size: "39", inStock: true, quantity: 0 },
          { size: "40", inStock: true, quantity: 4 },
          { size: "41", inStock: true, quantity: 9 },
          { size: "42", inStock: true, quantity: 11 },
          { size: "43", inStock: true, quantity: 4 },
          { size: "44", inStock: true, quantity: 8 },
          { size: "45", inStock: false, quantity: 2 },
          { size: "46", inStock: true, quantity: 3 },
          { size: "47", inStock: true, quantity: 1 },
        ],
      },
    ],
  },
  {
    productId: "stan-smith",
    name: "Adidas Stan Smith",
    brand: "Adidas",
    basePrice: 119.99,
    category: "Shoes",
    gender: "Male",
    variations: [
      {
        id: "stan-smith-white",
        colorway: "Blanc",
        price: 119.99,
        salePrice: null,
        thumbnailUrl: "/sneakers/thumbnails/Stan_Smith_Blanc_S75104_sm.webp",
        largeUrl: "/sneakers/large/Stan_Smith_Blanc_S75104.webp",
        alt: "Adidas Stan Smith Blanc",
        sizes: [
          { size: "38", inStock: true, quantity: 0 },
          { size: "39", inStock: false, quantity: 3 },
          { size: "40", inStock: true, quantity: 9 },
          { size: "41", inStock: true, quantity: 10 },
          { size: "42", inStock: true, quantity: 5 },
          { size: "43", inStock: true, quantity: 11 },
          { size: "44", inStock: true, quantity: 3 },
          { size: "45", inStock: true, quantity: 5 },
          { size: "46", inStock: false, quantity: 3 },
          { size: "47", inStock: true, quantity: 0 },
        ],
      },
      {
        id: "stan-smith",
        colorway: "Blanc/Bleu",
        price: 119.99,
        salePrice: null,
        thumbnailUrl: "/sneakers/thumbnails/Stan_Smith_Blanc_M20325_sm.webp",
        largeUrl: "/sneakers/large/Stan_Smith_Blanc_M20325.webp",
        alt: "Adidas Samba OG Blanc/Bleu",
        sizes: [
          { size: "38", inStock: false, quantity: 2 },
          { size: "39", inStock: true, quantity: 5 },
          { size: "40", inStock: true, quantity: 7 },
          { size: "41", inStock: true, quantity: 9 },
          { size: "42", inStock: true, quantity: 13 },
          { size: "43", inStock: true, quantity: 4 },
          { size: "44", inStock: true, quantity: 4 },
          { size: "45", inStock: false, quantity: 2 },
          { size: "46", inStock: true, quantity: 3 },
          { size: "47", inStock: true, quantity: 0 },
        ],
      },
      {
        id: "stan-smith-black",
        colorway: "Noir",
        price: 119.99,
        salePrice: null,
        thumbnailUrl: "/sneakers/thumbnails/Stan_Smith_Noir_M20327_sm.webp",
        largeUrl: "/sneakers/large/Stan_Smith_Noir_M20327.webp",
        alt: "Adidas Stan Smith Noir",
        sizes: [
          { size: "38", inStock: true, quantity: 2 },
          { size: "39", inStock: false, quantity: 1 },
          { size: "40", inStock: true, quantity: 9 },
          { size: "41", inStock: true, quantity: 8 },
          { size: "42", inStock: true, quantity: 3 },
          { size: "43", inStock: true, quantity: 11 },
          { size: "44", inStock: true, quantity: 3 },
          { size: "45", inStock: true, quantity: 4 },
          { size: "46", inStock: false, quantity: 0 },
          { size: "47", inStock: true, quantity: 0 },
        ],
      },
    ],
  },

  // CLOTHING CATEGORY
  {
    productId: "adidas-t-shirt-power-oversize",
    name: "T-Shirt Power Oversize",
    brand: "Adidas",
    basePrice: 29.99,
    category: "clothing",
    gender: "Male",
    variations: [
      {
        id: "power-oversize-blue",
        colorway: "Bleu",
        price: 29.99,
        salePrice: 24.99,
        thumbnailUrl:
          "/clothing/thumbnails/T-shirt_Power_Oversize_Bleu_JV9685_sm.webp",
        largeUrl: "/clothing/large/T-shirt_Power_Oversize_Bleu_JV9685.webp",
        alt: "Adidas T-Shirt Power Oversize Bleu",
        sizes: [
          { size: "XS", inStock: true, quantity: 12 },
          { size: "S", inStock: true, quantity: 25 },
          { size: "M", inStock: true, quantity: 30 },
          { size: "L", inStock: true, quantity: 22 },
          { size: "XL", inStock: true, quantity: 15 },
          { size: "XXL", inStock: true, quantity: 8 },
        ],
      },
      {
        id: "power-oversize-black",
        colorway: "Noir",
        price: 29.99,
        salePrice: 24.99,
        thumbnailUrl:
          "/clothing/thumbnails/T-shirt_Power_Oversize_Noir_JN3680_sm.webp",
        largeUrl: "/clothing/large/T-shirt_Power_Oversize_Noir_JN3680.webp",
        alt: "Adidas T-Shirt Power Oversize Noir",
        sizes: [
          { size: "XS", inStock: true, quantity: 2 },
          { size: "S", inStock: true, quantity: 18 },
          { size: "M", inStock: true, quantity: 28 },
          { size: "L", inStock: true, quantity: 27 },
          { size: "XL", inStock: true, quantity: 15 },
          { size: "XXL", inStock: true, quantity: 8 },
        ],
      },
    ],
  },
];

async function main() {
  console.log("Seeding database...");

  for (const productData of productsData) {
    const { variations, ...product } = productData;

    console.log(`Creating product: ${product.name}`);

    const createdProduct = await prisma.product.create({
      data: {
        ...product,
        variations: {
          create: variations.map((variation) => {
            const { sizes, ...variationData } = variation;
            return {
              ...variationData,
              sizes: {
                create: sizes,
              },
            };
          }),
        },
      },
      include: {
        variations: {
          include: {
            sizes: true,
          },
        },
      },
    });

    console.log(
      `Created ${createdProduct.name} with ${createdProduct.variations.length} variations`
    );
  }

  console.log("Seeding completed!");
}

main()
  .catch((e) => {
    console.error("Seeding failed:", e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
