import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import HeaderDisplayCondition from "@/components/layout/HeaderDisplayCondition";
import { AuthProvider } from "@/components/auth/AuthProvider";
import FooterDisplayCondition from "@/components/layout/FooterDisplayCondition";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
          <HeaderDisplayCondition />

          <main>{children}</main>

          <FooterDisplayCondition />
        </AuthProvider>
      </body>
    </html>
  );
}
